name: Steam Status Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # Cada 5 minutos (UTC)
  workflow_dispatch:        # Tambi√©n puedes lanzarlo manualmente

jobs:
  check-steam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests matplotlib
      - run: python monitor.py
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
