name: Steam Status Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # cada 5 min UTC
  workflow_dispatch:

jobs:
  check-steam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # <--- Muy importante para poder push

      - name: Initialize JSON files
        run: |
          [ -f state.json ] || echo '{}' > state.json
          [ -f history.json ] || echo '[]' > history.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests matplotlib

      - name: Run Steamstat monitor
        run: python monitor.py
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Commit JSON history
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -f state.json ] && [ -f history.json ]; then
            git add state.json history.json
            git commit -m "Update Steam history [skip ci]" || echo "No changes"
            git push
          else
            echo "JSON files not found, skipping commit"
          fi
