name: Steam Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # cada 5 minutos
  workflow_dispatch:       # permite ejecutar manualmente

jobs:
  check-steam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Steam Monitor
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: python monitor.py
