name: Steam Monitor

on:
  schedule:
    - cron: '*/5 * * * *' # se ejecuta cada 10 minutos
  workflow_dispatch:       # permite ejecutarlo manualmente

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Steam Monitor
        env:
          WEBHOOK_URLS_CHANGES: ${{ secrets.WEBHOOK_URLS_CHANGES }}
          WEBHOOK_URL_ERRORS: ${{ secrets.WEBHOOK_URL_ERRORS }}
        run: node monitor.js

      - name: Commit estado.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add estado.json
          # Solo commit si hay cambios
          git diff --cached --quiet || git commit -m "Update estado.json"
          git push
